spring:
  application:
    name: minicat
  
  # SQLite configuration for task storage
  datasource:
    url: jdbc:sqlite:/Users/joshuasiu/learning/minicat/data/tasks.db
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # JSON configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# CORS configuration
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Application configuration
minicat:
  storage:
    base-path: /Users/joshuasiu/learning/minicat/data
    connections-file: connections.json
    app-config-file: app_config.json
    diffs-path: diffs
  logs:
    retention-days: 7
    path: /Users/joshuasiu/learning/minicat/logs
  security:
    # AES 加密密钥（生产环境应使用环境变量）
    encryption-key: minicat-default-secret-key-2024

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
